# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Estado.create(id: 1, sigla: 'AC', nome: 'ACRE', ibge: 12)
Estado.create(id: 2, sigla: 'AL', nome: 'ALAGOAS', ibge: 27)
Estado.create(id: 3, sigla: 'AP', nome: 'AMAPÁ', ibge: 16)
Estado.create(id: 4, sigla: 'AM', nome: 'AMAZONAS', ibge: 13)
Estado.create(id: 5, sigla: 'BA', nome: 'BAHIA', ibge: 29)
Estado.create(id: 6, sigla: 'CE', nome: 'CEARÁ', ibge: 23)
Estado.create(id: 7, sigla: 'DF', nome: 'DISTRÍTO FEDERAL', ibge: 53)
Estado.create(id: 8, sigla: 'ES', nome: 'ESPÍRITO SANTO', ibge: 32)
Estado.create(id: 9, sigla: 'GO', nome: 'GOIÁS', ibge: 52)
Estado.create(id: 10, sigla: 'MA', nome: 'MARANHÃO', ibge: 21)
Estado.create(id: 11, sigla: 'MT', nome: 'MATO GROSSO', ibge: 51)
Estado.create(id: 12, sigla: 'MS', nome: 'MATO GROSSO DO SUL', ibge: 50)
Estado.create(id: 13, sigla: 'MG', nome: 'MINAS GERAIS', ibge: 31)
Estado.create(id: 14, sigla: 'PA', nome: 'PARÁ', ibge: 15)
Estado.create(id: 15, sigla: 'PB', nome: 'PARAÍBA', ibge: 25)
Estado.create(id: 16, sigla: 'PR', nome: 'PARANÁ', ibge: 41)
Estado.create(id: 17, sigla: 'PE', nome: 'PERNAMBUCO', ibge: 26)
Estado.create(id: 18, sigla: 'PI', nome: 'PIAUÍ', ibge: 22)
Estado.create(id: 19, sigla: 'RJ', nome: 'RIO DE JANEIRO', ibge: 31)
Estado.create(id: 20, sigla: 'RN', nome: 'RIO GRANDE DO NORTE', ibge: 24)
Estado.create(id: 21, sigla: 'RS', nome: 'RIO GRANDE DO SUL', ibge: 43)
Estado.create(id: 22, sigla: 'RO', nome: 'RONDÔNIA', ibge: 11)
Estado.create(id: 23, sigla: 'RR', nome: 'RORAIMA', ibge: 14)
Estado.create(id: 24, sigla: 'SC', nome: 'SANTA CATARINA', ibge: 42)
Estado.create(id: 25, sigla: 'SP', nome: 'SÃO PAULO', ibge: 35)
Estado.create(id: 26, sigla: 'SE', nome: 'SERGIPE', ibge: 28)
Estado.create(id: 27, sigla: 'TO', nome: 'TOCANTINS', ibge: 17)
